2020-12-21 18:33:45.708 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:33:45.709 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:33:45.710 [error] <0.308.0> CRASH REPORT Process <0.308.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"products.json">>,reason => enoent} in 'Elixir.File':'read!'/1 line 354 in application_master:init/4 line 138
2020-12-21 18:34:11.447 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:34:11.449 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:34:11.449 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"./products.json">>,reason => enoent} in 'Elixir.File':'read!'/1 line 354 in application_master:init/4 line 138
2020-12-21 18:36:01.741 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:36:01.743 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:36:01.747 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"./products.json">>,reason => enoent} in 'Elixir.File':'read!'/1 line 354 in application_master:init/4 line 138
2020-12-21 18:36:52.329 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:36:52.331 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:36:52.334 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"./products.json">>,reason => enoent} in 'Elixir.File':'read!'/1 line 354 in application_master:init/4 line 138
2020-12-21 18:39:54.548 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:39:54.550 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:39:54.552 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"/home/etienne/rabbitmq_project/_build/dev/lib/calc/lib/products.json">>,reason => enoent} in 'Elixir.File':'read!'/1 line 354 in application_master:init/4 line 138
2020-12-21 18:42:22.564 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:42:22.566 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:42:22.580 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 18:45:56.292 [error] <0.293.0>@Elixir.CALC.Agent:handle_call:18 gen_server banane_agent terminated with reason: no function clause matching 'Elixir.CALC.Agent':handle_call({add,10}, {<0.298.0>,#Ref<0.3563171291.904921091.196483>}, #{amount => 10,key => <<"banane">>}) line 18
2020-12-21 18:45:56.292 [error] <0.293.0>@Elixir.CALC.Agent:handle_call:18 CRASH REPORT Process <0.293.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Agent':handle_call({add,10}, {<0.298.0>,#Ref<0.3563171291.904921091.196483>}, #{amount => 10,key => <<"banane">>}) line 18
2020-12-21 18:45:56.292 [error] <0.288.0>@Elixir.CALC.Agent:handle_call:18 Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.293.0> exit with reason no function clause matching 'Elixir.CALC.Agent':handle_call({add,10}, {<0.298.0>,#Ref<0.3563171291.904921091.196483>}, #{amount => 10,key => <<"banane">>}) line 18 in context child_terminated
2020-12-21 18:47:09.628 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:47:09.630 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:47:09.646 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 18:48:15.041 [error] <0.294.0> gen_server banane_agent terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 18:48:15.041 [error] <0.294.0> CRASH REPORT Process <0.294.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 18:48:15.041 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.294.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822 in context child_terminated
2020-12-21 18:51:34.102 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:51:34.103 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:51:34.120 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 18:52:24.608 [error] <0.294.0> gen_server banane_agent terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 18:52:24.608 [error] <0.294.0> CRASH REPORT Process <0.294.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 18:52:24.608 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.294.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822 in context child_terminated
2020-12-21 18:55:33.355 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:55:33.356 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:55:33.424 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 18:57:03.865 [error] <0.279.0> gen_server banane_agent terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.279.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 18:57:03.865 [error] <0.279.0> CRASH REPORT Process <0.279.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.279.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 18:57:03.865 [error] <0.274.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.279.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.279.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822 in context child_terminated
2020-12-21 18:59:34.690 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:59:34.692 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:59:34.708 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 19:00:05.049 [error] <0.294.0> gen_server banane_agent terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 19:00:05.050 [error] <0.294.0> CRASH REPORT Process <0.294.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 19:00:05.051 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.294.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822 in context child_terminated
2020-12-21 19:02:28.800 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 19:02:28.802 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 19:02:28.819 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 19:51:50.682 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 19:51:50.683 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 19:51:50.684 [error] <0.300.0> Supervisor 'Elixir.CALC.MainSupervisor' had child <<"resupply">> started with 'Elixir.CALC.Resupply':start() at undefined exit with reason {'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_s..."},...]}]}} in context start_error
2020-12-21 19:51:50.693 [error] <0.298.0>@Elixir.GenServer:call CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.CALC.AgentSupervisor', {start_child,{{'Elixir.CALC.Agent',start,[<<"banane">>,10]},transient,5000,worker,['Elixir.CALC.Agent']}}, infinity) in application_master:init/4 line 138
2020-12-21 19:53:35.950 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 19:53:35.952 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 19:53:35.955 [error] <0.299.0> Supervisor 'Elixir.CALC.MainSupervisor' had child <<"resupply">> started with 'Elixir.CALC.Resupply':start() at undefined exit with reason {'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_s..."},...]}]}} in context start_error
2020-12-21 19:53:35.962 [error] <0.297.0>@Elixir.GenServer:call CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.CALC.AgentSupervisor', {start_child,{{'Elixir.CALC.Agent',start,[<<"banane">>,10]},transient,5000,worker,['Elixir.CALC.Agent']}}, infinity) in application_master:init/4 line 138
2020-12-21 19:56:16.774 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 19:56:16.776 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 19:56:16.780 [error] <0.287.0> Supervisor 'Elixir.CALC.MainSupervisor' had child 1 started with 'Elixir.CALC.Resupply':start() at undefined exit with reason {'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_s..."},...]}]}} in context start_error
2020-12-21 19:56:16.787 [error] <0.285.0>@Elixir.GenServer:call CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.CALC.AgentSupervisor', {start_child,{{'Elixir.CALC.Agent',start,[<<"banane">>,10]},transient,5000,worker,['Elixir.CALC.Agent']}}, infinity) in application_master:init/4 line 138
2020-12-21 19:56:44.411 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 19:56:44.412 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 19:56:44.416 [error] <0.287.0> Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at undefined exit with reason {'EXIT',{undef,[{'Elixir.CALC.Resupply',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,...},...]}]}} in context start_error
2020-12-21 19:56:44.424 [error] <0.285.0>@Elixir.GenServer:call CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.CALC.AgentSupervisor', {start_child,{{'Elixir.CALC.Agent',start,[<<"banane">>,10]},transient,5000,worker,['Elixir.CALC.Agent']}}, infinity) in application_master:init/4 line 138
2020-12-21 20:00:16.693 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:00:16.694 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:00:16.697 [error] <0.287.0> Supervisor 'Elixir.CALC.MainSupervisor' had child <<"resupply">> started with 'Elixir.CALC.Resupply':start() at undefined exit with reason {'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_s..."},...]}]}} in context start_error
2020-12-21 20:00:16.698 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {error,{shutdown,{failed_to_start_child,<<"resupply">>,{'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,...},...]},...]}}}}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in application_master:init/4 line 138
2020-12-21 20:01:48.253 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:01:48.254 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:01:48.258 [error] <0.287.0> Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at undefined exit with reason {'EXIT',{undef,[{'Elixir.CALC.Resupply',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,...},...]}]}} in context start_error
2020-12-21 20:01:48.258 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {error,{shutdown,{failed_to_start_child,'Elixir.CALC.Resupply',{'EXIT',{undef,[{'Elixir.CALC.Resupply',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,...},...]}}}}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in application_master:init/4 line 138
2020-12-21 20:02:22.587 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:02:22.588 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:02:22.589 [error] <0.286.0> CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<0.288.0>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in application_master:init/4 line 138
2020-12-21 20:03:34.820 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:03:34.821 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:03:34.833 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 20:06:10.049 [error] <0.289.0> gen_server resupply terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>} in 'Elixir.CALC.Resupply':handle_call/3 line 777
2020-12-21 20:06:10.050 [error] <0.289.0> CRASH REPORT Process <0.289.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>} in 'Elixir.CALC.Resupply':handle_call/3 line 777
2020-12-21 20:06:10.050 [error] <0.287.0> Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.289.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>} in 'Elixir.CALC.Resupply':handle_call/3 line 777 in context child_terminated
2020-12-21 20:06:10.057 [error] <0.295.0> gen_server banane_agent terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>},[{'Elixir.CALC.Resupply',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.289.0>,{resupply,<0.295.0>},...]}} in 'Elixir.GenServer':call/3 line 1027
2020-12-21 20:06:10.057 [error] <0.295.0> CRASH REPORT Process <0.295.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>},[{'Elixir.CALC.Resupply',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.289.0>,{resupply,<0.295.0>},...]}} in 'Elixir.GenServer':call/3 line 1027
2020-12-21 20:06:10.058 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.295.0> exit with reason {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>},[{'Elixir.CALC.Resupply',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.289.0>,{resupply,<0.295.0>},...]}} in context child_terminated
2020-12-21 20:07:07.501 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:07:07.502 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:07:07.518 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 20:07:25.917 [error] <0.290.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.296.0>}, []) line 14
2020-12-21 20:07:25.918 [error] <0.290.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.290.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.296.0>}, []) line 14
2020-12-21 20:07:25.918 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.290.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.296.0>}, []) line 14 in context child_terminated
2020-12-21 20:13:27.213 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:13:27.214 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:13:27.230 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 20:13:46.559 [error] <0.290.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.296.0>}, []) line 14
2020-12-21 20:13:46.559 [error] <0.290.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.290.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.296.0>}, []) line 14
2020-12-21 20:13:46.559 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.290.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.296.0>}, []) line 14 in context child_terminated
2020-12-21 20:14:44.724 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:14:44.725 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:14:44.741 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 20:15:04.747 [error] <0.296.0>@Elixir.CALC.Agent:handle_call:20 gen_server banane_agent terminated with reason: no function clause matching 'Elixir.CALC.Agent':handle_call({add,10}, {<0.290.0>,#Ref<0.2979725000.2797600773.136215>}, #{amount => 1,key => <<"banane">>}) line 20
2020-12-21 20:15:04.747 [error] <0.296.0>@Elixir.CALC.Agent:handle_call:20 CRASH REPORT Process <0.296.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Agent':handle_call({add,10}, {<0.290.0>,#Ref<0.2979725000.2797600773.136215>}, #{amount => 1,key => <<"banane">>}) line 20
2020-12-21 20:15:04.747 [error] <0.289.0>@Elixir.CALC.Agent:handle_call:20 Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.296.0> exit with reason no function clause matching 'Elixir.CALC.Agent':handle_call({add,10}, {<0.290.0>,#Ref<0.2979725000.2797600773.136215>}, #{amount => 1,key => <<"banane">>}) line 20 in context child_terminated
2020-12-21 20:15:04.748 [error] <0.290.0> gen_server resupply terminated with reason: {{function_clause,[{'Elixir.CALC.Agent',handle_call,[{add,10},{<0.290.0>,#Ref<0.2979725000.2797600773.136215>},#{amount => 1,key => <<"banane">>}],[{file,"lib/agent.ex"},{line,20}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.296.0>,{add,10},5000]}} in 'Elixir.GenServer':call/3 line 1027
2020-12-21 20:15:04.748 [error] <0.290.0> CRASH REPORT Process <0.290.0> with 0 neighbours exited with reason: {{function_clause,[{'Elixir.CALC.Agent',handle_call,[{add,10},{<0.290.0>,#Ref<0.2979725000.2797600773.136215>},#{amount => 1,key => <<"banane">>}],[{file,"lib/agent.ex"},{line,20}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.296.0>,{add,10},5000]}} in 'Elixir.GenServer':call/3 line 1027
2020-12-21 20:15:04.749 [error] <0.288.0> Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.290.0> exit with reason {{function_clause,[{'Elixir.CALC.Agent',handle_call,[{add,10},{<0.290.0>,#Ref<0.2979725000.2797600773.136215>},#{amount => 1,key => <<"banane">>}],[{file,"lib/agent.ex"},{line,20}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.296.0>,{add,10},5000]}} in context child_terminated
2020-12-21 20:16:33.443 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:16:33.444 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:16:33.459 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 20:43:45.921 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:43:45.923 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:43:45.941 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 20:44:33.643 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:44:33.644 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:44:33.668 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 21:23:51.985 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 21:23:51.986 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 21:23:55.452 [error] <0.290.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.298.0>}, [<0.300.0>|<0.297.0>]) line 14
2020-12-21 21:23:55.452 [error] <0.290.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.290.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.298.0>}, [<0.300.0>|<0.297.0>]) line 14
2020-12-21 21:23:55.452 [error] <0.287.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.290.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.298.0>}, [<0.300.0>|<0.297.0>]) line 14 in context child_terminated
2020-12-21 21:24:52.505 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 21:24:52.506 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 21:25:02.520 [error] <0.291.0>@Elixir.GenServer:cast:1058 gen_server resupply terminated with reason: no function clause matching 'Elixir.GenServer':cast([[[[]|<0.297.0>]|<0.299.0>]|<0.298.0>], {add,10}) line 1058
2020-12-21 21:25:02.521 [error] <0.291.0>@Elixir.GenServer:cast:1058 CRASH REPORT Process <0.291.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.GenServer':cast([[[[]|<0.297.0>]|<0.299.0>]|<0.298.0>], {add,10}) line 1058
2020-12-21 21:25:02.521 [error] <0.288.0>@Elixir.GenServer:cast:1058 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.291.0> exit with reason no function clause matching 'Elixir.GenServer':cast([[[[]|<0.297.0>]|<0.299.0>]|<0.298.0>], {add,10}) line 1058 in context child_terminated
2020-12-21 21:26:15.864 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 21:26:15.866 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 21:26:21.722 [error] <0.297.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.303.0>}, [<0.304.0>|<0.305.0>]) line 14
2020-12-21 21:26:21.723 [error] <0.297.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.297.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.303.0>}, [<0.304.0>|<0.305.0>]) line 14
2020-12-21 21:26:21.723 [error] <0.294.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.297.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.303.0>}, [<0.304.0>|<0.305.0>]) line 14 in context child_terminated
2020-12-21 21:26:27.031 [error] <0.308.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.306.0>}, [<0.305.0>|<0.307.0>]) line 14
2020-12-21 21:26:27.032 [error] <0.308.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.308.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.306.0>}, [<0.305.0>|<0.307.0>]) line 14
2020-12-21 21:26:27.032 [error] <0.294.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.308.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.306.0>}, [<0.305.0>|<0.307.0>]) line 14 in context child_terminated
2020-12-21 21:28:58.600 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 21:28:58.601 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 21:29:03.283 [error] <0.291.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.299.0>}, [<0.301.0>|<0.297.0>]) line 14
2020-12-21 21:29:03.284 [error] <0.291.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.291.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.299.0>}, [<0.301.0>|<0.297.0>]) line 14
2020-12-21 21:29:03.285 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.291.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.299.0>}, [<0.301.0>|<0.297.0>]) line 14 in context child_terminated
2020-12-21 21:29:07.270 [error] <0.302.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.301.0>}, [<0.300.0>|<0.298.0>]) line 14
2020-12-21 21:29:07.270 [error] <0.302.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.302.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.301.0>}, [<0.300.0>|<0.298.0>]) line 14
2020-12-21 21:29:07.270 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.302.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.301.0>}, [<0.300.0>|<0.298.0>]) line 14 in context child_terminated
2020-12-21 21:29:07.548 [error] <0.304.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.298.0>}, [<0.299.0>|<0.297.0>]) line 14
2020-12-21 21:29:07.548 [error] <0.304.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.304.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.298.0>}, [<0.299.0>|<0.297.0>]) line 14
2020-12-21 21:29:07.548 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.304.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.298.0>}, [<0.299.0>|<0.297.0>]) line 14 in context child_terminated
2020-12-21 21:29:47.287 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 21:29:47.287 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 21:29:49.576 [error] <0.291.0>@Elixir.CALC.Resupply:handle_cast:18 gen_server resupply terminated with reason: bad argument in call to erlang:'++'([<0.301.0>|<0.300.0>], <0.299.0>) in 'Elixir.CALC.Resupply':handle_cast/2 line 18
2020-12-21 21:29:49.576 [error] <0.291.0>@Elixir.CALC.Resupply:handle_cast:18 CRASH REPORT Process <0.291.0> with 0 neighbours crashed with reason: bad argument in call to erlang:'++'([<0.301.0>|<0.300.0>], <0.299.0>) in 'Elixir.CALC.Resupply':handle_cast/2 line 18
2020-12-21 21:29:49.576 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:18 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.291.0> exit with reason bad argument in call to erlang:'++'([<0.301.0>|<0.300.0>], <0.299.0>) in 'Elixir.CALC.Resupply':handle_cast/2 line 18 in context child_terminated
2020-12-21 21:29:51.850 [error] <0.302.0>@Elixir.CALC.Resupply:handle_cast:18 gen_server resupply terminated with reason: bad argument in call to erlang:'++'([<0.300.0>|<0.301.0>], <0.298.0>) in 'Elixir.CALC.Resupply':handle_cast/2 line 18
2020-12-21 21:29:51.851 [error] <0.302.0>@Elixir.CALC.Resupply:handle_cast:18 CRASH REPORT Process <0.302.0> with 0 neighbours crashed with reason: bad argument in call to erlang:'++'([<0.300.0>|<0.301.0>], <0.298.0>) in 'Elixir.CALC.Resupply':handle_cast/2 line 18
2020-12-21 21:29:51.851 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:18 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.302.0> exit with reason bad argument in call to erlang:'++'([<0.300.0>|<0.301.0>], <0.298.0>) in 'Elixir.CALC.Resupply':handle_cast/2 line 18 in context child_terminated
2020-12-21 21:31:47.864 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 21:31:47.865 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 21:33:11.636 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 21:33:11.637 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 21:34:59.165 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 21:34:59.167 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:09:46.542 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:09:46.544 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:09:46.573 [error] <0.305.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:09:46.573 [error] <0.305.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.305.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:09:46.573 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.296.0>) at <0.305.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:09:46.574 [error] <0.303.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:09:46.574 [error] <0.303.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.303.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:09:46.574 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.296.0>) at <0.303.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:09:46.575 [error] <0.302.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:09:46.575 [error] <0.302.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.302.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:09:46.575 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.296.0>) at <0.302.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:09:46.576 [error] <0.306.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:09:46.576 [error] <0.306.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.306.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:09:46.576 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.296.0>) at <0.306.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:09:46.576 [error] <0.304.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:09:46.576 [error] <0.304.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.304.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:09:46.577 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.296.0>) at <0.304.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:09:46.577 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:14:32.771 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:14:32.772 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:14:32.800 [error] <0.298.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:14:32.800 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:14:32.800 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.290.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:14:32.801 [error] <0.299.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:14:32.801 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:14:32.801 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.290.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:14:32.802 [error] <0.296.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:14:32.802 [error] <0.296.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.296.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:14:32.802 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.290.0>) at <0.296.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:14:32.802 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:16:41.298 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:16:41.300 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:16:41.328 [error] <0.305.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:16:41.328 [error] <0.305.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.305.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:16:41.328 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.296.0>) at <0.305.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:16:41.329 [error] <0.306.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:16:41.329 [error] <0.306.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.306.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:16:41.329 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.296.0>) at <0.306.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:16:41.329 [error] <0.303.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:16:41.330 [error] <0.303.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.303.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:16:41.330 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.296.0>) at <0.303.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:16:41.330 [error] <0.302.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:16:41.330 [error] <0.302.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.302.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:16:41.330 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.296.0>) at <0.302.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:16:41.330 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:19:54.570 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:19:54.572 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:19:54.602 [error] <0.300.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:19:54.602 [error] <0.300.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:19:54.602 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.291.0>) at <0.300.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:19:54.603 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:19:54.603 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:19:54.603 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:19:54.603 [error] <0.298.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:19:54.603 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:19:54.603 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.291.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:19:54.603 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:20:51.237 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:20:51.239 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:20:51.269 [error] <0.300.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:20:51.269 [error] <0.300.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:20:51.270 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.291.0>) at <0.300.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:20:51.270 [error] <0.298.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:20:51.270 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:20:51.270 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.291.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:20:51.271 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:20:51.271 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:20:51.271 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:20:51.271 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:21:10.734 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:21:10.736 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:21:10.764 [error] <0.297.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:21:10.764 [error] <0.297.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:21:10.764 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.291.0>) at <0.297.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:21:10.765 [error] <0.299.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:21:10.765 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:21:10.765 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.291.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:21:10.766 [error] <0.298.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:21:10.766 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:21:10.766 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.291.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:21:10.767 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:21:10.767 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:21:10.767 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:21:10.767 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:22:36.763 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:22:36.764 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:22:36.793 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:22:36.793 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:22:36.793 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:22:36.794 [error] <0.297.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:22:36.794 [error] <0.297.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:22:36.794 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.291.0>) at <0.297.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:22:36.795 [error] <0.299.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:22:36.795 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:22:36.795 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.291.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:22:36.795 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:23:43.689 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:23:43.691 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:23:43.722 [error] <0.297.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:23:43.722 [error] <0.297.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:23:43.722 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.291.0>) at <0.297.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:23:43.723 [error] <0.300.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:23:43.723 [error] <0.300.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:23:43.723 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.291.0>) at <0.300.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:23:43.723 [error] <0.299.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:23:43.723 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:23:43.724 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.291.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:23:43.724 [error] <0.298.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:23:43.724 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:23:43.724 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.291.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:23:43.725 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:23:43.725 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:23:43.725 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:23:43.725 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:24:31.706 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:24:31.708 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:24:31.738 [error] <0.298.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:24:31.739 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:24:31.739 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.291.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:24:31.739 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:24:31.739 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:24:31.739 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:24:31.740 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:26:22.129 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:26:22.130 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:26:22.158 [error] <0.296.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:26:22.158 [error] <0.296.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.296.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:26:22.161 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.290.0>) at <0.296.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:26:22.161 [error] <0.299.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:26:22.161 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:26:22.161 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.290.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:26:22.161 [error] <0.298.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:26:22.162 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:26:22.162 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.290.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:26:22.162 [error] <0.300.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:26:22.162 [error] <0.300.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:26:22.162 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.290.0>) at <0.300.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:26:22.162 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:28:56.593 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:28:56.594 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:28:56.620 [error] <0.300.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:28:56.620 [error] <0.300.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:28:56.624 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.291.0>) at <0.300.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:28:56.624 [error] <0.297.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:28:56.624 [error] <0.297.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:28:56.624 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.291.0>) at <0.297.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:28:56.624 [error] <0.299.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:28:56.624 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:28:56.624 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.291.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:28:56.624 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:28:56.624 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:28:56.624 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:28:56.624 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:29:46.505 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:29:46.507 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:29:46.531 [error] <0.298.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:29:46.532 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:29:46.534 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.291.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:29:46.534 [error] <0.297.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:29:46.534 [error] <0.297.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:29:46.535 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.291.0>) at <0.297.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:29:46.535 [error] <0.299.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:29:46.535 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:29:46.535 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.291.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:29:46.535 [error] <0.300.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:29:46.535 [error] <0.300.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:29:46.535 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.291.0>) at <0.300.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:33:02.348 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:33:02.349 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:33:39.414 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:33:39.415 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 23:14:40.060 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 23:14:40.062 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 23:15:28.705 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 23:15:28.706 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 23:15:28.727 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 23:16:08.888 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 23:16:08.889 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 23:16:08.909 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 23:16:26.263 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 23:16:26.264 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 23:17:16.942 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 23:17:16.943 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 23:17:16.959 [error] <0.282.0>@Elixir.CALC.Agent:init:11 CRASH REPORT Process <0.282.0> with 0 neighbours crashed with reason: no match of right hand value 2 in 'Elixir.CALC.Agent':init/1 line 11
2020-12-21 23:17:16.959 [error] <0.283.0>@Elixir.CALC.Agent:init:11 CRASH REPORT Process <0.283.0> with 0 neighbours crashed with reason: no match of right hand value 2 in 'Elixir.CALC.Agent':init/1 line 11
2020-12-21 23:17:16.959 [error] <0.284.0>@Elixir.CALC.Agent:init:11 CRASH REPORT Process <0.284.0> with 0 neighbours crashed with reason: no match of right hand value 2 in 'Elixir.CALC.Agent':init/1 line 11
2020-12-21 23:17:16.960 [error] <0.285.0>@Elixir.CALC.Agent:init:11 CRASH REPORT Process <0.285.0> with 0 neighbours crashed with reason: no match of right hand value 2 in 'Elixir.CALC.Agent':init/1 line 11
2020-12-21 23:17:16.960 [error] <0.286.0>@Elixir.CALC.Agent:init:11 CRASH REPORT Process <0.286.0> with 0 neighbours crashed with reason: no match of right hand value 2 in 'Elixir.CALC.Agent':init/1 line 11
2020-12-21 23:45:23.531 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 23:45:23.533 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 23:49:26.020 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 23:49:26.021 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 14:30:31.052 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 14:30:31.053 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 14:32:18.736 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 14:32:18.737 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 14:32:18.804 [error] <0.316.0>@Elixir.CALC.Agent:handle_continue:47 gen_server peche_agent terminated with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:18.804 [error] <0.313.0>@Elixir.CALC.Agent:handle_continue:47 gen_server framboise_agent terminated with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:18.804 [error] <0.312.0>@Elixir.CALC.Agent:handle_continue:47 gen_server banane_agent terminated with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:18.804 [error] <0.315.0>@Elixir.CALC.Agent:handle_continue:47 gen_server poire_agent terminated with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:18.804 [error] <0.315.0>@Elixir.CALC.Agent:handle_continue:47 CRASH REPORT Process <0.315.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:18.804 [error] <0.316.0>@Elixir.CALC.Agent:handle_continue:47 CRASH REPORT Process <0.316.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:18.804 [error] <0.312.0>@Elixir.CALC.Agent:handle_continue:47 CRASH REPORT Process <0.312.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:18.804 [error] <0.313.0>@Elixir.CALC.Agent:handle_continue:47 CRASH REPORT Process <0.313.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:18.805 [error] <0.304.0>@Elixir.CALC.Agent:handle_continue:47 Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.306.0>, #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},...}) at <0.315.0> exit with reason no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47 in context child_terminated
2020-12-22 14:32:18.805 [error] <0.304.0>@Elixir.CALC.Agent:handle_continue:47 Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.306.0>, #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},...}) at <0.316.0> exit with reason no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47 in context child_terminated
2020-12-22 14:32:18.805 [error] <0.304.0>@Elixir.CALC.Agent:handle_continue:47 Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.306.0>, #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},...}) at <0.312.0> exit with reason no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47 in context child_terminated
2020-12-22 14:32:18.805 [error] <0.304.0>@Elixir.CALC.Agent:handle_continue:47 Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.306.0>, #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},...}) at <0.313.0> exit with reason no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47 in context child_terminated
2020-12-22 14:32:19.710 [error] <0.314.0>@Elixir.CALC.Agent:handle_continue:47 gen_server pomme_agent terminated with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:19.711 [error] <0.314.0>@Elixir.CALC.Agent:handle_continue:47 CRASH REPORT Process <0.314.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:19.711 [error] <0.304.0>@Elixir.CALC.Agent:handle_continue:47 Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.306.0>, #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},...}) at <0.314.0> exit with reason no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47 in context child_terminated
2020-12-22 14:32:19.711 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-22 14:34:48.192 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 14:34:48.193 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 14:35:59.123 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 14:35:59.124 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 14:36:59.621 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 14:36:59.622 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 14:50:00.744 [info] <0.44.0> Application lager started on node nonode@nohost
2020-12-22 14:50:00.744 [info] <0.44.0> Application jsx started on node nonode@nohost
2020-12-22 14:50:00.744 [info] <0.44.0> Application ranch started on node nonode@nohost
2020-12-22 14:50:00.744 [info] <0.44.0> Application recon started on node nonode@nohost
2020-12-22 14:50:00.750 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2020-12-22 14:50:00.750 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2020-12-22 14:50:00.751 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2020-12-22 14:52:07.271 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 14:52:07.273 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 14:54:07.172 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 14:54:07.173 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 15:19:17.952 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 15:19:17.953 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 15:20:21.258 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 15:20:21.259 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 15:20:39.275 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 15:20:39.277 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 15:24:18.471 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 15:24:18.474 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 15:24:18.523 [error] <0.294.0> Supervisor 'Elixir.CALC.ClientSupervisor' had child <<"clientTest">> started with 'Elixir.CALC.Client':init(<<"toto">>, [<<"peche.5">>]) at undefined exit with reason {'EXIT',{{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'calc_exchange' in vhost '/'">>}},{gen_server,call,[<0.308.0>,{subscribe,{'basic.consume',0,<<"calc_exchange">>,<<>>,false,true,false,false,[]},<0.310.0>},60000]}}} in context start_error
2020-12-22 15:24:18.523 [error] <0.292.0> CRASH REPORT Process <0.292.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,<<"clientTest">>,{'EXIT',{{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'calc_exchange' in vhost '/'">>}},{gen_server,call,[<0.308.0>,{subscribe,{'basic.consume',0,<<"calc_exchange">>,<<>>,false,true,false,false,[]},<0.310.0>},60000]}}}}},{'Elixir.CALC.Application',start,[normal,[]]}} in application_master:init/4 line 138
2020-12-22 15:24:26.739 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 15:24:26.741 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 15:24:29.627 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 15:24:29.628 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 15:24:29.673 [error] <0.279.0> Supervisor 'Elixir.CALC.ClientSupervisor' had child <<"clientTest">> started with 'Elixir.CALC.Client':init(<<"toto">>, [<<"peche.5">>]) at undefined exit with reason {'EXIT',{{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'calc_exchange' in vhost '/'">>}},{gen_server,call,[<0.293.0>,{subscribe,{'basic.consume',0,<<"calc_exchange">>,<<>>,false,true,false,false,[]},<0.295.0>},60000]}}} in context start_error
2020-12-22 15:25:09.833 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 15:25:09.834 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 15:25:12.369 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 15:25:12.371 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 15:28:04.515 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 15:28:04.516 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 15:28:26.220 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 15:28:26.221 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 16:11:25.111 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 16:11:25.113 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 16:11:31.171 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:11:31.172 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:11:31.181 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:12:25.521 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:12:25.523 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:12:25.531 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:14:22.479 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:14:22.481 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:14:22.491 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:14:54.560 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:14:54.562 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:14:54.571 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:16:15.270 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:16:15.272 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:16:15.282 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:16:47.831 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:16:47.833 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:16:47.893 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:22:34.167 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:22:34.174 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:22:34.189 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:23:21.446 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:23:21.448 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:23:21.458 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:24:30.002 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:24:30.003 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:24:30.013 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:26:41.691 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:26:41.692 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:26:41.702 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:30:35.627 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:30:35.629 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:30:35.639 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:32:09.814 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:32:09.816 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:32:09.826 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:32:55.971 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:32:55.972 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:32:55.988 [error] <0.291.0> CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 138
2020-12-22 16:36:03.098 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:36:03.100 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:36:03.115 [error] <0.291.0> CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 138
2020-12-22 16:38:11.383 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:38:11.385 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:38:11.401 [error] <0.291.0> CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 138
2020-12-22 16:40:26.171 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:40:26.173 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:40:26.186 [error] <0.293.0>@ok:init CRASH REPORT Process <0.293.0> with 0 neighbours crashed with reason: call to undefined function ok:init([{strategy,one_for_one},{name,'Elixir.CALC.ClientSupervisor'}])
2020-12-22 16:40:26.186 [error] <0.291.0> CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: {{undef,[{ok,init,[[{strategy,one_for_one},{name,'Elixir.CALC.ClientSupervisor'}]],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,301}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.CALC.Application',start,[normal,[]]}} in application_master:init/4 line 138
2020-12-22 16:41:06.091 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:41:06.093 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:41:06.104 [error] <0.291.0> CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: {{undef,[{ok,init,[[{strategy,one_for_one},{name,'Elixir.CALC.ClientSupervisor'}]],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,301}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.CALC.Application',start,[normal,[]]}} in application_master:init/4 line 138
2020-12-22 16:41:06.104 [error] <0.293.0>@ok:init CRASH REPORT Process <0.293.0> with 0 neighbours crashed with reason: call to undefined function ok:init([{strategy,one_for_one},{name,'Elixir.CALC.ClientSupervisor'}])
2020-12-22 16:45:16.547 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:45:16.549 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:45:16.561 [error] <0.293.0>@ok:init CRASH REPORT Process <0.293.0> with 0 neighbours crashed with reason: call to undefined function ok:init([{strategy,one_for_one},{name,'Elixir.CALC.ClientSupervisor'}])
2020-12-22 16:45:16.562 [error] <0.291.0> CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: {{undef,[{ok,init,[[{strategy,one_for_one},{name,'Elixir.CALC.ClientSupervisor'}]],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,301}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.CALC.Application',start,[normal,[]]}} in application_master:init/4 line 138
2020-12-22 16:45:45.984 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:45:45.986 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:47:09.786 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:47:09.789 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:47:31.890 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 16:47:31.892 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 16:49:12.497 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:49:12.499 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:51:12.328 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:51:12.330 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:52:18.335 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:52:18.337 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:53:37.303 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:53:37.305 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 16:59:11.082 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 16:59:11.083 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 17:01:05.328 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:01:05.329 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:03:56.123 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:03:56.124 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:05:32.499 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:05:32.501 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:17:07.919 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:17:07.921 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:17:08.069 [error] <0.299.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-e7mRKZCZ5lzAvRQJ3VS15Q">>}}
2020-12-22 17:17:08.070 [error] <0.299.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-ZDWJ4j_Y1F_jNcpVnKPJ7Q">>}}
2020-12-22 17:17:08.070 [error] <0.299.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-NULE9VqCrk0lObFBA0H2hg">>}}
2020-12-22 17:17:08.070 [error] <0.299.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-7ukL10Qrmn10b-78j9w4Tg">>}}
2020-12-22 17:17:08.070 [error] <0.299.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-VWRuHMr5N0xLCjDOjzCJMw">>}}
2020-12-22 17:17:08.071 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:25:43.175 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:25:43.176 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:25:43.351 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:25:43.351 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-rgcjzJ6QmtCIuKnKPPXEWw">>}}
2020-12-22 17:25:43.351 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-LzP_YmXhAg914_QIQZnM2Q">>}}
2020-12-22 17:25:43.351 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-lrWMukaTLbnkCM6dspy8hQ">>}}
2020-12-22 17:25:43.351 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-H-fuq4ATEAldHhqUZ2pQuQ">>}}
2020-12-22 17:25:43.351 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-w1x7xTBhqlH2u1WCpwxbYw">>}}
2020-12-22 17:27:20.155 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:27:20.156 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:27:20.337 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-n8onPFjX_NV93E1nrL1SfA">>}}
2020-12-22 17:27:20.337 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-x8BKSY2A7FPTV5HTggl7LQ">>}}
2020-12-22 17:27:20.337 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-fpF5-yZftk1edZ0V2qgrZg">>}}
2020-12-22 17:27:20.338 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-ZIDiIC3tlyDcHi4MtJsJkw">>}}
2020-12-22 17:27:20.338 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:27:20.338 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-v83aa3mCvnRiv7F2uEZ14Q">>}}
2020-12-22 17:28:26.024 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:28:26.025 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:28:26.092 [error] <0.294.0> Supervisor 'Elixir.CALC.ClientSupervisor' had child <<"1">> started with 'Elixir.CALC.Client':init(<<"client_1">>, [<<"framboise.0">>]) at undefined exit with reason {'EXIT',{{badmatch,<0.311.0>},[{'Elixir.CALC.Client',init,2,[{file,"lib/client.ex"},{line,15}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,...}]},...]}} in context start_error
2020-12-22 17:28:26.092 [error] <0.292.0> CRASH REPORT Process <0.292.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,<<"1">>,{'EXIT',{{badmatch,<0.311.0>},[{'Elixir.CALC.Client',init,2,[{file,"lib/client.ex"},{line,15}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,...},...]}}}},...} in application_master:init/4 line 138
2020-12-22 17:29:26.028 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:29:26.029 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:29:26.251 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-3t75e0uGpHbL7fLwMeKclg">>}}
2020-12-22 17:29:26.251 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 17:29:26.251 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-5FtIXQQDICaL65arC3ASCw">>}}
2020-12-22 17:29:26.252 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-qgNJBOs0sPXbhJRoI6jGQw">>}}
2020-12-22 17:29:26.252 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-31OLQvu0VMPjBJn2aFKMFA">>}}
2020-12-22 17:29:26.253 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-owt3xyssdHFF3e4yc6Fjyg">>}}
2020-12-22 18:09:42.922 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:09:42.923 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:09:42.935 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:10:02.140 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 18:10:02.141 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 18:16:32.764 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:16:32.766 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:16:32.777 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:16:59.644 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 18:16:59.645 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 18:40:59.479 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 18:40:59.480 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 18:42:03.567 [error] <0.334.0> gen_server <0.334.0> terminated with reason: socket_closed_unexpectedly
2020-12-22 18:42:03.568 [error] <0.337.0> gen_server <0.337.0> terminated with reason: socket_closed_unexpectedly
2020-12-22 18:42:03.568 [error] <0.340.0> gen_server <0.340.0> terminated with reason: socket_closed_unexpectedly
2020-12-22 18:42:03.568 [error] <0.331.0> gen_server <0.331.0> terminated with reason: socket_closed_unexpectedly
2020-12-22 18:42:03.569 [error] <0.328.0> gen_server <0.328.0> terminated with reason: socket_closed_unexpectedly
2020-12-22 18:42:03.569 [error] <0.328.0> CRASH REPORT Process <0.328.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 796
2020-12-22 18:42:03.570 [error] <0.337.0> CRASH REPORT Process <0.337.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 796
2020-12-22 18:42:03.570 [error] <0.334.0> CRASH REPORT Process <0.334.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 796
2020-12-22 18:42:03.570 [error] <0.331.0> CRASH REPORT Process <0.331.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 796
2020-12-22 18:42:03.570 [error] <0.340.0> CRASH REPORT Process <0.340.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 796
2020-12-22 18:42:03.570 [error] <0.325.0> Supervisor {<0.325.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.327.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.328.0> exit with reason socket_closed_unexpectedly in context child_terminated
2020-12-22 18:42:03.570 [error] <0.329.0> Supervisor {<0.329.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.330.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.331.0> exit with reason socket_closed_unexpectedly in context child_terminated
2020-12-22 18:42:03.570 [error] <0.325.0> Supervisor {<0.325.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.327.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.328.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-22 18:42:03.571 [error] <0.329.0> Supervisor {<0.329.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.330.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.331.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-22 18:42:03.571 [error] <0.335.0> Supervisor {<0.335.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.336.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.337.0> exit with reason socket_closed_unexpectedly in context child_terminated
2020-12-22 18:42:03.571 [error] <0.335.0> Supervisor {<0.335.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.336.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.337.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-22 18:42:03.571 [error] <0.338.0> Supervisor {<0.338.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.339.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.340.0> exit with reason socket_closed_unexpectedly in context child_terminated
2020-12-22 18:42:03.571 [error] <0.338.0> Supervisor {<0.338.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.339.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.340.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-22 18:42:03.571 [error] <0.332.0> Supervisor {<0.332.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.333.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.334.0> exit with reason socket_closed_unexpectedly in context child_terminated
2020-12-22 18:42:03.572 [error] <0.332.0> Supervisor {<0.332.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.333.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.334.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-22 18:42:15.172 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:42:15.173 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:42:15.187 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:43:35.419 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:43:35.420 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:43:35.432 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:45:52.680 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:45:52.681 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:45:52.694 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:50:44.147 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:50:44.148 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:50:44.159 [error] <0.291.0>@Elixir.CALC.Application:start CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: bad return value ok from 'Elixir.CALC.Application':start(normal, []) in application_master:init/4 line 138
2020-12-22 18:51:23.494 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:51:23.496 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:51:23.508 [error] <0.291.0>@Elixir.CALC.Application:start CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: bad return value ok from 'Elixir.CALC.Application':start(normal, []) in application_master:init/4 line 138
2020-12-22 18:51:44.449 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:51:44.451 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:51:44.459 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:52:57.128 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 18:52:57.129 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 18:54:57.600 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 18:54:57.602 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 18:55:03.383 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:55:03.384 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 18:55:03.399 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:00:01.654 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:00:01.655 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:00:01.667 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:01:09.231 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 19:01:09.233 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 19:09:35.793 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:09:35.795 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:09:35.807 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:09:43.111 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 19:09:43.112 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 19:20:21.822 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:20:21.824 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:20:21.837 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:21:01.734 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 19:21:01.735 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 19:21:07.646 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:21:07.648 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:21:07.660 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:21:33.502 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:21:33.503 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:21:33.515 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:45:04.722 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:45:04.724 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:46:16.455 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 19:46:16.456 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 19:46:20.659 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:46:20.660 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:48:05.885 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 19:48:05.886 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 20:03:34.450 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 20:03:34.451 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 20:03:41.523 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 20:03:41.524 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 20:04:17.336 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 20:04:17.337 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 20:06:48.979 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-22 20:06:48.981 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-22 20:06:54.415 [info] <0.44.0> Application logger started on node 'client@etienne-Inspiron-7380'
2020-12-22 20:06:54.416 [info] <0.44.0> Application poison started on node 'client@etienne-Inspiron-7380'
2020-12-22 20:06:54.429 [info] <0.44.0> Application calc started on node 'client@etienne-Inspiron-7380'
