2020-12-21 18:33:45.708 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:33:45.709 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:33:45.710 [error] <0.308.0> CRASH REPORT Process <0.308.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"products.json">>,reason => enoent} in 'Elixir.File':'read!'/1 line 354 in application_master:init/4 line 138
2020-12-21 18:34:11.447 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:34:11.449 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:34:11.449 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"./products.json">>,reason => enoent} in 'Elixir.File':'read!'/1 line 354 in application_master:init/4 line 138
2020-12-21 18:36:01.741 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:36:01.743 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:36:01.747 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"./products.json">>,reason => enoent} in 'Elixir.File':'read!'/1 line 354 in application_master:init/4 line 138
2020-12-21 18:36:52.329 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:36:52.331 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:36:52.334 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"./products.json">>,reason => enoent} in 'Elixir.File':'read!'/1 line 354 in application_master:init/4 line 138
2020-12-21 18:39:54.548 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:39:54.550 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:39:54.552 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"/home/etienne/rabbitmq_project/_build/dev/lib/calc/lib/products.json">>,reason => enoent} in 'Elixir.File':'read!'/1 line 354 in application_master:init/4 line 138
2020-12-21 18:42:22.564 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:42:22.566 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:42:22.580 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 18:45:56.292 [error] <0.293.0>@Elixir.CALC.Agent:handle_call:18 gen_server banane_agent terminated with reason: no function clause matching 'Elixir.CALC.Agent':handle_call({add,10}, {<0.298.0>,#Ref<0.3563171291.904921091.196483>}, #{amount => 10,key => <<"banane">>}) line 18
2020-12-21 18:45:56.292 [error] <0.293.0>@Elixir.CALC.Agent:handle_call:18 CRASH REPORT Process <0.293.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Agent':handle_call({add,10}, {<0.298.0>,#Ref<0.3563171291.904921091.196483>}, #{amount => 10,key => <<"banane">>}) line 18
2020-12-21 18:45:56.292 [error] <0.288.0>@Elixir.CALC.Agent:handle_call:18 Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.293.0> exit with reason no function clause matching 'Elixir.CALC.Agent':handle_call({add,10}, {<0.298.0>,#Ref<0.3563171291.904921091.196483>}, #{amount => 10,key => <<"banane">>}) line 18 in context child_terminated
2020-12-21 18:47:09.628 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:47:09.630 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:47:09.646 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 18:48:15.041 [error] <0.294.0> gen_server banane_agent terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 18:48:15.041 [error] <0.294.0> CRASH REPORT Process <0.294.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 18:48:15.041 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.294.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822 in context child_terminated
2020-12-21 18:51:34.102 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:51:34.103 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:51:34.120 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 18:52:24.608 [error] <0.294.0> gen_server banane_agent terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 18:52:24.608 [error] <0.294.0> CRASH REPORT Process <0.294.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 18:52:24.608 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.294.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822 in context child_terminated
2020-12-21 18:55:33.355 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:55:33.356 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:55:33.424 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 18:57:03.865 [error] <0.279.0> gen_server banane_agent terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.279.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 18:57:03.865 [error] <0.279.0> CRASH REPORT Process <0.279.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.279.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 18:57:03.865 [error] <0.274.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.279.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.279.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822 in context child_terminated
2020-12-21 18:59:34.690 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 18:59:34.692 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 18:59:34.708 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 19:00:05.049 [error] <0.294.0> gen_server banane_agent terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 19:00:05.050 [error] <0.294.0> CRASH REPORT Process <0.294.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 19:00:05.051 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.294.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822 in context child_terminated
2020-12-21 19:02:28.800 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 19:02:28.802 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 19:02:28.819 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 19:51:50.682 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 19:51:50.683 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 19:51:50.684 [error] <0.300.0> Supervisor 'Elixir.CALC.MainSupervisor' had child <<"resupply">> started with 'Elixir.CALC.Resupply':start() at undefined exit with reason {'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_s..."},...]}]}} in context start_error
2020-12-21 19:51:50.693 [error] <0.298.0>@Elixir.GenServer:call CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.CALC.AgentSupervisor', {start_child,{{'Elixir.CALC.Agent',start,[<<"banane">>,10]},transient,5000,worker,['Elixir.CALC.Agent']}}, infinity) in application_master:init/4 line 138
2020-12-21 19:53:35.950 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 19:53:35.952 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 19:53:35.955 [error] <0.299.0> Supervisor 'Elixir.CALC.MainSupervisor' had child <<"resupply">> started with 'Elixir.CALC.Resupply':start() at undefined exit with reason {'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_s..."},...]}]}} in context start_error
2020-12-21 19:53:35.962 [error] <0.297.0>@Elixir.GenServer:call CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.CALC.AgentSupervisor', {start_child,{{'Elixir.CALC.Agent',start,[<<"banane">>,10]},transient,5000,worker,['Elixir.CALC.Agent']}}, infinity) in application_master:init/4 line 138
2020-12-21 19:56:16.774 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 19:56:16.776 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 19:56:16.780 [error] <0.287.0> Supervisor 'Elixir.CALC.MainSupervisor' had child 1 started with 'Elixir.CALC.Resupply':start() at undefined exit with reason {'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_s..."},...]}]}} in context start_error
2020-12-21 19:56:16.787 [error] <0.285.0>@Elixir.GenServer:call CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.CALC.AgentSupervisor', {start_child,{{'Elixir.CALC.Agent',start,[<<"banane">>,10]},transient,5000,worker,['Elixir.CALC.Agent']}}, infinity) in application_master:init/4 line 138
2020-12-21 19:56:44.411 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 19:56:44.412 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 19:56:44.416 [error] <0.287.0> Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at undefined exit with reason {'EXIT',{undef,[{'Elixir.CALC.Resupply',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,...},...]}]}} in context start_error
2020-12-21 19:56:44.424 [error] <0.285.0>@Elixir.GenServer:call CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.CALC.AgentSupervisor', {start_child,{{'Elixir.CALC.Agent',start,[<<"banane">>,10]},transient,5000,worker,['Elixir.CALC.Agent']}}, infinity) in application_master:init/4 line 138
2020-12-21 20:00:16.693 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:00:16.694 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:00:16.697 [error] <0.287.0> Supervisor 'Elixir.CALC.MainSupervisor' had child <<"resupply">> started with 'Elixir.CALC.Resupply':start() at undefined exit with reason {'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_s..."},...]}]}} in context start_error
2020-12-21 20:00:16.698 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {error,{shutdown,{failed_to_start_child,<<"resupply">>,{'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,...},...]},...]}}}}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in application_master:init/4 line 138
2020-12-21 20:01:48.253 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:01:48.254 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:01:48.258 [error] <0.287.0> Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at undefined exit with reason {'EXIT',{undef,[{'Elixir.CALC.Resupply',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,...},...]}]}} in context start_error
2020-12-21 20:01:48.258 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {error,{shutdown,{failed_to_start_child,'Elixir.CALC.Resupply',{'EXIT',{undef,[{'Elixir.CALC.Resupply',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,...},...]}}}}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in application_master:init/4 line 138
2020-12-21 20:02:22.587 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:02:22.588 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:02:22.589 [error] <0.286.0> CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<0.288.0>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in application_master:init/4 line 138
2020-12-21 20:03:34.820 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:03:34.821 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:03:34.833 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 20:06:10.049 [error] <0.289.0> gen_server resupply terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>} in 'Elixir.CALC.Resupply':handle_call/3 line 777
2020-12-21 20:06:10.050 [error] <0.289.0> CRASH REPORT Process <0.289.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>} in 'Elixir.CALC.Resupply':handle_call/3 line 777
2020-12-21 20:06:10.050 [error] <0.287.0> Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.289.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>} in 'Elixir.CALC.Resupply':handle_call/3 line 777 in context child_terminated
2020-12-21 20:06:10.057 [error] <0.295.0> gen_server banane_agent terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>},[{'Elixir.CALC.Resupply',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.289.0>,{resupply,<0.295.0>},...]}} in 'Elixir.GenServer':call/3 line 1027
2020-12-21 20:06:10.057 [error] <0.295.0> CRASH REPORT Process <0.295.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>},[{'Elixir.CALC.Resupply',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.289.0>,{resupply,<0.295.0>},...]}} in 'Elixir.GenServer':call/3 line 1027
2020-12-21 20:06:10.058 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.295.0> exit with reason {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>},[{'Elixir.CALC.Resupply',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.289.0>,{resupply,<0.295.0>},...]}} in context child_terminated
2020-12-21 20:07:07.501 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:07:07.502 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:07:07.518 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 20:07:25.917 [error] <0.290.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.296.0>}, []) line 14
2020-12-21 20:07:25.918 [error] <0.290.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.290.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.296.0>}, []) line 14
2020-12-21 20:07:25.918 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.290.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.296.0>}, []) line 14 in context child_terminated
2020-12-21 20:13:27.213 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:13:27.214 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:13:27.230 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 20:13:46.559 [error] <0.290.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.296.0>}, []) line 14
2020-12-21 20:13:46.559 [error] <0.290.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.290.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.296.0>}, []) line 14
2020-12-21 20:13:46.559 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.290.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.296.0>}, []) line 14 in context child_terminated
2020-12-21 20:14:44.724 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:14:44.725 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:14:44.741 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 20:15:04.747 [error] <0.296.0>@Elixir.CALC.Agent:handle_call:20 gen_server banane_agent terminated with reason: no function clause matching 'Elixir.CALC.Agent':handle_call({add,10}, {<0.290.0>,#Ref<0.2979725000.2797600773.136215>}, #{amount => 1,key => <<"banane">>}) line 20
2020-12-21 20:15:04.747 [error] <0.296.0>@Elixir.CALC.Agent:handle_call:20 CRASH REPORT Process <0.296.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Agent':handle_call({add,10}, {<0.290.0>,#Ref<0.2979725000.2797600773.136215>}, #{amount => 1,key => <<"banane">>}) line 20
2020-12-21 20:15:04.747 [error] <0.289.0>@Elixir.CALC.Agent:handle_call:20 Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.296.0> exit with reason no function clause matching 'Elixir.CALC.Agent':handle_call({add,10}, {<0.290.0>,#Ref<0.2979725000.2797600773.136215>}, #{amount => 1,key => <<"banane">>}) line 20 in context child_terminated
2020-12-21 20:15:04.748 [error] <0.290.0> gen_server resupply terminated with reason: {{function_clause,[{'Elixir.CALC.Agent',handle_call,[{add,10},{<0.290.0>,#Ref<0.2979725000.2797600773.136215>},#{amount => 1,key => <<"banane">>}],[{file,"lib/agent.ex"},{line,20}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.296.0>,{add,10},5000]}} in 'Elixir.GenServer':call/3 line 1027
2020-12-21 20:15:04.748 [error] <0.290.0> CRASH REPORT Process <0.290.0> with 0 neighbours exited with reason: {{function_clause,[{'Elixir.CALC.Agent',handle_call,[{add,10},{<0.290.0>,#Ref<0.2979725000.2797600773.136215>},#{amount => 1,key => <<"banane">>}],[{file,"lib/agent.ex"},{line,20}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.296.0>,{add,10},5000]}} in 'Elixir.GenServer':call/3 line 1027
2020-12-21 20:15:04.749 [error] <0.288.0> Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.290.0> exit with reason {{function_clause,[{'Elixir.CALC.Agent',handle_call,[{add,10},{<0.290.0>,#Ref<0.2979725000.2797600773.136215>},#{amount => 1,key => <<"banane">>}],[{file,"lib/agent.ex"},{line,20}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.296.0>,{add,10},5000]}} in context child_terminated
2020-12-21 20:16:33.443 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:16:33.444 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:16:33.459 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 20:43:45.921 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:43:45.923 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:43:45.941 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 20:44:33.643 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 20:44:33.644 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 20:44:33.668 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 21:23:51.985 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 21:23:51.986 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 21:23:55.452 [error] <0.290.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.298.0>}, [<0.300.0>|<0.297.0>]) line 14
2020-12-21 21:23:55.452 [error] <0.290.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.290.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.298.0>}, [<0.300.0>|<0.297.0>]) line 14
2020-12-21 21:23:55.452 [error] <0.287.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.290.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.298.0>}, [<0.300.0>|<0.297.0>]) line 14 in context child_terminated
2020-12-21 21:24:52.505 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 21:24:52.506 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 21:25:02.520 [error] <0.291.0>@Elixir.GenServer:cast:1058 gen_server resupply terminated with reason: no function clause matching 'Elixir.GenServer':cast([[[[]|<0.297.0>]|<0.299.0>]|<0.298.0>], {add,10}) line 1058
2020-12-21 21:25:02.521 [error] <0.291.0>@Elixir.GenServer:cast:1058 CRASH REPORT Process <0.291.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.GenServer':cast([[[[]|<0.297.0>]|<0.299.0>]|<0.298.0>], {add,10}) line 1058
2020-12-21 21:25:02.521 [error] <0.288.0>@Elixir.GenServer:cast:1058 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.291.0> exit with reason no function clause matching 'Elixir.GenServer':cast([[[[]|<0.297.0>]|<0.299.0>]|<0.298.0>], {add,10}) line 1058 in context child_terminated
2020-12-21 21:26:15.864 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 21:26:15.866 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 21:26:21.722 [error] <0.297.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.303.0>}, [<0.304.0>|<0.305.0>]) line 14
2020-12-21 21:26:21.723 [error] <0.297.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.297.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.303.0>}, [<0.304.0>|<0.305.0>]) line 14
2020-12-21 21:26:21.723 [error] <0.294.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.297.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.303.0>}, [<0.304.0>|<0.305.0>]) line 14 in context child_terminated
2020-12-21 21:26:27.031 [error] <0.308.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.306.0>}, [<0.305.0>|<0.307.0>]) line 14
2020-12-21 21:26:27.032 [error] <0.308.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.308.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.306.0>}, [<0.305.0>|<0.307.0>]) line 14
2020-12-21 21:26:27.032 [error] <0.294.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.308.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.306.0>}, [<0.305.0>|<0.307.0>]) line 14 in context child_terminated
2020-12-21 21:28:58.600 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 21:28:58.601 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 21:29:03.283 [error] <0.291.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.299.0>}, [<0.301.0>|<0.297.0>]) line 14
2020-12-21 21:29:03.284 [error] <0.291.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.291.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.299.0>}, [<0.301.0>|<0.297.0>]) line 14
2020-12-21 21:29:03.285 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.291.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.299.0>}, [<0.301.0>|<0.297.0>]) line 14 in context child_terminated
2020-12-21 21:29:07.270 [error] <0.302.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.301.0>}, [<0.300.0>|<0.298.0>]) line 14
2020-12-21 21:29:07.270 [error] <0.302.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.302.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.301.0>}, [<0.300.0>|<0.298.0>]) line 14
2020-12-21 21:29:07.270 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.302.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.301.0>}, [<0.300.0>|<0.298.0>]) line 14 in context child_terminated
2020-12-21 21:29:07.548 [error] <0.304.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.298.0>}, [<0.299.0>|<0.297.0>]) line 14
2020-12-21 21:29:07.548 [error] <0.304.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.304.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.298.0>}, [<0.299.0>|<0.297.0>]) line 14
2020-12-21 21:29:07.548 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.304.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.298.0>}, [<0.299.0>|<0.297.0>]) line 14 in context child_terminated
2020-12-21 21:29:47.287 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 21:29:47.287 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 21:29:49.576 [error] <0.291.0>@Elixir.CALC.Resupply:handle_cast:18 gen_server resupply terminated with reason: bad argument in call to erlang:'++'([<0.301.0>|<0.300.0>], <0.299.0>) in 'Elixir.CALC.Resupply':handle_cast/2 line 18
2020-12-21 21:29:49.576 [error] <0.291.0>@Elixir.CALC.Resupply:handle_cast:18 CRASH REPORT Process <0.291.0> with 0 neighbours crashed with reason: bad argument in call to erlang:'++'([<0.301.0>|<0.300.0>], <0.299.0>) in 'Elixir.CALC.Resupply':handle_cast/2 line 18
2020-12-21 21:29:49.576 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:18 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.291.0> exit with reason bad argument in call to erlang:'++'([<0.301.0>|<0.300.0>], <0.299.0>) in 'Elixir.CALC.Resupply':handle_cast/2 line 18 in context child_terminated
2020-12-21 21:29:51.850 [error] <0.302.0>@Elixir.CALC.Resupply:handle_cast:18 gen_server resupply terminated with reason: bad argument in call to erlang:'++'([<0.300.0>|<0.301.0>], <0.298.0>) in 'Elixir.CALC.Resupply':handle_cast/2 line 18
2020-12-21 21:29:51.851 [error] <0.302.0>@Elixir.CALC.Resupply:handle_cast:18 CRASH REPORT Process <0.302.0> with 0 neighbours crashed with reason: bad argument in call to erlang:'++'([<0.300.0>|<0.301.0>], <0.298.0>) in 'Elixir.CALC.Resupply':handle_cast/2 line 18
2020-12-21 21:29:51.851 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:18 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.302.0> exit with reason bad argument in call to erlang:'++'([<0.300.0>|<0.301.0>], <0.298.0>) in 'Elixir.CALC.Resupply':handle_cast/2 line 18 in context child_terminated
2020-12-21 21:31:47.864 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 21:31:47.865 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 21:33:11.636 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 21:33:11.637 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 21:34:59.165 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 21:34:59.167 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:09:46.542 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:09:46.544 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:09:46.573 [error] <0.305.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:09:46.573 [error] <0.305.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.305.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:09:46.573 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.296.0>) at <0.305.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:09:46.574 [error] <0.303.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:09:46.574 [error] <0.303.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.303.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:09:46.574 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.296.0>) at <0.303.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:09:46.575 [error] <0.302.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:09:46.575 [error] <0.302.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.302.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:09:46.575 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.296.0>) at <0.302.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:09:46.576 [error] <0.306.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:09:46.576 [error] <0.306.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.306.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:09:46.576 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.296.0>) at <0.306.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:09:46.576 [error] <0.304.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:09:46.576 [error] <0.304.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.304.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:09:46.577 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.296.0>) at <0.304.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:09:46.577 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:14:32.771 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:14:32.772 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:14:32.800 [error] <0.298.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:14:32.800 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:14:32.800 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.290.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:14:32.801 [error] <0.299.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:14:32.801 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:14:32.801 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.290.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:14:32.802 [error] <0.296.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:14:32.802 [error] <0.296.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.296.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:14:32.802 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.290.0>) at <0.296.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:14:32.802 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:16:41.298 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:16:41.300 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:16:41.328 [error] <0.305.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:16:41.328 [error] <0.305.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.305.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:16:41.328 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.296.0>) at <0.305.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:16:41.329 [error] <0.306.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:16:41.329 [error] <0.306.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.306.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:16:41.329 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.296.0>) at <0.306.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:16:41.329 [error] <0.303.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:16:41.330 [error] <0.303.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.303.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:16:41.330 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.296.0>) at <0.303.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:16:41.330 [error] <0.302.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:16:41.330 [error] <0.302.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.302.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:16:41.330 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.296.0>) at <0.302.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:16:41.330 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:19:54.570 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:19:54.572 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:19:54.602 [error] <0.300.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:19:54.602 [error] <0.300.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:19:54.602 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.291.0>) at <0.300.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:19:54.603 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:19:54.603 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:19:54.603 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:19:54.603 [error] <0.298.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:19:54.603 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:19:54.603 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.291.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:19:54.603 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:20:51.237 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:20:51.239 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:20:51.269 [error] <0.300.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:20:51.269 [error] <0.300.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:20:51.270 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.291.0>) at <0.300.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:20:51.270 [error] <0.298.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:20:51.270 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:20:51.270 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.291.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:20:51.271 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:20:51.271 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:20:51.271 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:20:51.271 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:21:10.734 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:21:10.736 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:21:10.764 [error] <0.297.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:21:10.764 [error] <0.297.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:21:10.764 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.291.0>) at <0.297.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:21:10.765 [error] <0.299.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:21:10.765 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:21:10.765 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.291.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:21:10.766 [error] <0.298.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:21:10.766 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:21:10.766 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.291.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:21:10.767 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:21:10.767 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:21:10.767 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:21:10.767 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:22:36.763 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:22:36.764 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:22:36.793 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:22:36.793 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:22:36.793 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:22:36.794 [error] <0.297.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:22:36.794 [error] <0.297.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:22:36.794 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.291.0>) at <0.297.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:22:36.795 [error] <0.299.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:22:36.795 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:22:36.795 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.291.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:22:36.795 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:23:43.689 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:23:43.691 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:23:43.722 [error] <0.297.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:23:43.722 [error] <0.297.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:23:43.722 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.291.0>) at <0.297.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:23:43.723 [error] <0.300.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:23:43.723 [error] <0.300.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:23:43.723 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.291.0>) at <0.300.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:23:43.723 [error] <0.299.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:23:43.723 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:23:43.724 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.291.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:23:43.724 [error] <0.298.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:23:43.724 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:23:43.724 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.291.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:23:43.725 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:23:43.725 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:23:43.725 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:23:43.725 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:24:31.706 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:24:31.708 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:24:31.738 [error] <0.298.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:24:31.739 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:24:31.739 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.291.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:24:31.739 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:24:31.739 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:24:31.739 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:24:31.740 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:26:22.129 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:26:22.130 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:26:22.158 [error] <0.296.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:26:22.158 [error] <0.296.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.296.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:26:22.161 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.290.0>) at <0.296.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:26:22.161 [error] <0.299.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:26:22.161 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:26:22.161 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.290.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:26:22.161 [error] <0.298.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:26:22.162 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:26:22.162 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.290.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:26:22.162 [error] <0.300.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:26:22.162 [error] <0.300.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:26:22.162 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.290.0>) at <0.300.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:26:22.162 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:28:56.593 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:28:56.594 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:28:56.620 [error] <0.300.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:28:56.620 [error] <0.300.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:28:56.624 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.291.0>) at <0.300.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:28:56.624 [error] <0.297.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:28:56.624 [error] <0.297.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:28:56.624 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.291.0>) at <0.297.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:28:56.624 [error] <0.299.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:28:56.624 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:28:56.624 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.291.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:28:56.624 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:28:56.624 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:28:56.624 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:28:56.624 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 22:29:46.505 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:29:46.507 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:29:46.531 [error] <0.298.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:29:46.532 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:29:46.534 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.291.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:29:46.534 [error] <0.297.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:29:46.534 [error] <0.297.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:29:46.535 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.291.0>) at <0.297.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:29:46.535 [error] <0.299.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:29:46.535 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:29:46.535 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.291.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:29:46.535 [error] <0.300.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:29:46.535 [error] <0.300.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:29:46.535 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.291.0>) at <0.300.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:33:02.348 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:33:02.349 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 22:33:39.414 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 22:33:39.415 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 23:14:40.060 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 23:14:40.062 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 23:15:28.705 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 23:15:28.706 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 23:15:28.727 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 23:16:08.888 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 23:16:08.889 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 23:16:08.909 [info] <0.44.0> Application calc started on node nonode@nohost
2020-12-21 23:16:26.263 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 23:16:26.264 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 23:17:16.942 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 23:17:16.943 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 23:17:16.959 [error] <0.282.0>@Elixir.CALC.Agent:init:11 CRASH REPORT Process <0.282.0> with 0 neighbours crashed with reason: no match of right hand value 2 in 'Elixir.CALC.Agent':init/1 line 11
2020-12-21 23:17:16.959 [error] <0.283.0>@Elixir.CALC.Agent:init:11 CRASH REPORT Process <0.283.0> with 0 neighbours crashed with reason: no match of right hand value 2 in 'Elixir.CALC.Agent':init/1 line 11
2020-12-21 23:17:16.959 [error] <0.284.0>@Elixir.CALC.Agent:init:11 CRASH REPORT Process <0.284.0> with 0 neighbours crashed with reason: no match of right hand value 2 in 'Elixir.CALC.Agent':init/1 line 11
2020-12-21 23:17:16.960 [error] <0.285.0>@Elixir.CALC.Agent:init:11 CRASH REPORT Process <0.285.0> with 0 neighbours crashed with reason: no match of right hand value 2 in 'Elixir.CALC.Agent':init/1 line 11
2020-12-21 23:17:16.960 [error] <0.286.0>@Elixir.CALC.Agent:init:11 CRASH REPORT Process <0.286.0> with 0 neighbours crashed with reason: no match of right hand value 2 in 'Elixir.CALC.Agent':init/1 line 11
2020-12-21 23:45:23.531 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 23:45:23.533 [info] <0.44.0> Application poison started on node nonode@nohost
2020-12-21 23:49:26.020 [info] <0.44.0> Application logger started on node nonode@nohost
2020-12-21 23:49:26.021 [info] <0.44.0> Application poison started on node nonode@nohost
