2020-12-21 18:34:11.449 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"./products.json">>,reason => enoent} in 'Elixir.File':'read!'/1 line 354 in application_master:init/4 line 138
2020-12-21 18:36:01.747 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"./products.json">>,reason => enoent} in 'Elixir.File':'read!'/1 line 354 in application_master:init/4 line 138
2020-12-21 18:36:52.334 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"./products.json">>,reason => enoent} in 'Elixir.File':'read!'/1 line 354 in application_master:init/4 line 138
2020-12-21 18:39:54.552 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"read file">>,path => <<"/home/etienne/rabbitmq_project/_build/dev/lib/calc/lib/products.json">>,reason => enoent} in 'Elixir.File':'read!'/1 line 354 in application_master:init/4 line 138
2020-12-21 18:45:56.292 [error] <0.293.0>@Elixir.CALC.Agent:handle_call:18 gen_server banane_agent terminated with reason: no function clause matching 'Elixir.CALC.Agent':handle_call({add,10}, {<0.298.0>,#Ref<0.3563171291.904921091.196483>}, #{amount => 10,key => <<"banane">>}) line 18
2020-12-21 18:45:56.292 [error] <0.293.0>@Elixir.CALC.Agent:handle_call:18 CRASH REPORT Process <0.293.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Agent':handle_call({add,10}, {<0.298.0>,#Ref<0.3563171291.904921091.196483>}, #{amount => 10,key => <<"banane">>}) line 18
2020-12-21 18:45:56.292 [error] <0.288.0>@Elixir.CALC.Agent:handle_call:18 Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.293.0> exit with reason no function clause matching 'Elixir.CALC.Agent':handle_call({add,10}, {<0.298.0>,#Ref<0.3563171291.904921091.196483>}, #{amount => 10,key => <<"banane">>}) line 18 in context child_terminated
2020-12-21 18:48:15.041 [error] <0.294.0> gen_server banane_agent terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 18:48:15.041 [error] <0.294.0> CRASH REPORT Process <0.294.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 18:48:15.041 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.294.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822 in context child_terminated
2020-12-21 18:52:24.608 [error] <0.294.0> gen_server banane_agent terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 18:52:24.608 [error] <0.294.0> CRASH REPORT Process <0.294.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 18:52:24.608 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.294.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822 in context child_terminated
2020-12-21 18:57:03.865 [error] <0.279.0> gen_server banane_agent terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.279.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 18:57:03.865 [error] <0.279.0> CRASH REPORT Process <0.279.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.279.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 18:57:03.865 [error] <0.274.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.279.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.279.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822 in context child_terminated
2020-12-21 19:00:05.049 [error] <0.294.0> gen_server banane_agent terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 19:00:05.050 [error] <0.294.0> CRASH REPORT Process <0.294.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822
2020-12-21 19:00:05.051 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.294.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer #PID<0.294.0> but no handle_cast/2 clause was provided">>} in 'Elixir.CALC.Agent':handle_cast/2 line 822 in context child_terminated
2020-12-21 19:51:50.684 [error] <0.300.0> Supervisor 'Elixir.CALC.MainSupervisor' had child <<"resupply">> started with 'Elixir.CALC.Resupply':start() at undefined exit with reason {'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_s..."},...]}]}} in context start_error
2020-12-21 19:51:50.693 [error] <0.298.0>@Elixir.GenServer:call CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.CALC.AgentSupervisor', {start_child,{{'Elixir.CALC.Agent',start,[<<"banane">>,10]},transient,5000,worker,['Elixir.CALC.Agent']}}, infinity) in application_master:init/4 line 138
2020-12-21 19:53:35.955 [error] <0.299.0> Supervisor 'Elixir.CALC.MainSupervisor' had child <<"resupply">> started with 'Elixir.CALC.Resupply':start() at undefined exit with reason {'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_s..."},...]}]}} in context start_error
2020-12-21 19:53:35.962 [error] <0.297.0>@Elixir.GenServer:call CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.CALC.AgentSupervisor', {start_child,{{'Elixir.CALC.Agent',start,[<<"banane">>,10]},transient,5000,worker,['Elixir.CALC.Agent']}}, infinity) in application_master:init/4 line 138
2020-12-21 19:56:16.780 [error] <0.287.0> Supervisor 'Elixir.CALC.MainSupervisor' had child 1 started with 'Elixir.CALC.Resupply':start() at undefined exit with reason {'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_s..."},...]}]}} in context start_error
2020-12-21 19:56:16.787 [error] <0.285.0>@Elixir.GenServer:call CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.CALC.AgentSupervisor', {start_child,{{'Elixir.CALC.Agent',start,[<<"banane">>,10]},transient,5000,worker,['Elixir.CALC.Agent']}}, infinity) in application_master:init/4 line 138
2020-12-21 19:56:44.416 [error] <0.287.0> Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at undefined exit with reason {'EXIT',{undef,[{'Elixir.CALC.Resupply',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,...},...]}]}} in context start_error
2020-12-21 19:56:44.424 [error] <0.285.0>@Elixir.GenServer:call CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.CALC.AgentSupervisor', {start_child,{{'Elixir.CALC.Agent',start,[<<"banane">>,10]},transient,5000,worker,['Elixir.CALC.Agent']}}, infinity) in application_master:init/4 line 138
2020-12-21 20:00:16.697 [error] <0.287.0> Supervisor 'Elixir.CALC.MainSupervisor' had child <<"resupply">> started with 'Elixir.CALC.Resupply':start() at undefined exit with reason {'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_s..."},...]}]}} in context start_error
2020-12-21 20:00:16.698 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {error,{shutdown,{failed_to_start_child,<<"resupply">>,{'EXIT',{undef,[{'Elixir.CALC.Resupply',start,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,...},...]},...]}}}}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in application_master:init/4 line 138
2020-12-21 20:01:48.258 [error] <0.287.0> Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at undefined exit with reason {'EXIT',{undef,[{'Elixir.CALC.Resupply',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,...},...]}]}} in context start_error
2020-12-21 20:01:48.258 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {error,{shutdown,{failed_to_start_child,'Elixir.CALC.Resupply',{'EXIT',{undef,[{'Elixir.CALC.Resupply',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,...},...]}}}}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in application_master:init/4 line 138
2020-12-21 20:02:22.589 [error] <0.286.0> CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<0.288.0>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in application_master:init/4 line 138
2020-12-21 20:06:10.049 [error] <0.289.0> gen_server resupply terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>} in 'Elixir.CALC.Resupply':handle_call/3 line 777
2020-12-21 20:06:10.050 [error] <0.289.0> CRASH REPORT Process <0.289.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>} in 'Elixir.CALC.Resupply':handle_call/3 line 777
2020-12-21 20:06:10.050 [error] <0.287.0> Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.289.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>} in 'Elixir.CALC.Resupply':handle_call/3 line 777 in context child_terminated
2020-12-21 20:06:10.057 [error] <0.295.0> gen_server banane_agent terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>},[{'Elixir.CALC.Resupply',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.289.0>,{resupply,<0.295.0>},...]}} in 'Elixir.GenServer':call/3 line 1027
2020-12-21 20:06:10.057 [error] <0.295.0> CRASH REPORT Process <0.295.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>},[{'Elixir.CALC.Resupply',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.289.0>,{resupply,<0.295.0>},...]}} in 'Elixir.GenServer':call/3 line 1027
2020-12-21 20:06:10.058 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.295.0> exit with reason {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer #PID<0.289.0> but no handle_call/3 clause was provided">>},[{'Elixir.CALC.Resupply',handle_call,3,[{file,"lib/gen_server.ex"},{line,777}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.289.0>,{resupply,<0.295.0>},...]}} in context child_terminated
2020-12-21 20:07:25.917 [error] <0.290.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.296.0>}, []) line 14
2020-12-21 20:07:25.918 [error] <0.290.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.290.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.296.0>}, []) line 14
2020-12-21 20:07:25.918 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.290.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.296.0>}, []) line 14 in context child_terminated
2020-12-21 20:13:46.559 [error] <0.290.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.296.0>}, []) line 14
2020-12-21 20:13:46.559 [error] <0.290.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.290.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.296.0>}, []) line 14
2020-12-21 20:13:46.559 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.290.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.296.0>}, []) line 14 in context child_terminated
2020-12-21 20:15:04.747 [error] <0.296.0>@Elixir.CALC.Agent:handle_call:20 gen_server banane_agent terminated with reason: no function clause matching 'Elixir.CALC.Agent':handle_call({add,10}, {<0.290.0>,#Ref<0.2979725000.2797600773.136215>}, #{amount => 1,key => <<"banane">>}) line 20
2020-12-21 20:15:04.747 [error] <0.296.0>@Elixir.CALC.Agent:handle_call:20 CRASH REPORT Process <0.296.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Agent':handle_call({add,10}, {<0.290.0>,#Ref<0.2979725000.2797600773.136215>}, #{amount => 1,key => <<"banane">>}) line 20
2020-12-21 20:15:04.747 [error] <0.289.0>@Elixir.CALC.Agent:handle_call:20 Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10) at <0.296.0> exit with reason no function clause matching 'Elixir.CALC.Agent':handle_call({add,10}, {<0.290.0>,#Ref<0.2979725000.2797600773.136215>}, #{amount => 1,key => <<"banane">>}) line 20 in context child_terminated
2020-12-21 20:15:04.748 [error] <0.290.0> gen_server resupply terminated with reason: {{function_clause,[{'Elixir.CALC.Agent',handle_call,[{add,10},{<0.290.0>,#Ref<0.2979725000.2797600773.136215>},#{amount => 1,key => <<"banane">>}],[{file,"lib/agent.ex"},{line,20}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.296.0>,{add,10},5000]}} in 'Elixir.GenServer':call/3 line 1027
2020-12-21 20:15:04.748 [error] <0.290.0> CRASH REPORT Process <0.290.0> with 0 neighbours exited with reason: {{function_clause,[{'Elixir.CALC.Agent',handle_call,[{add,10},{<0.290.0>,#Ref<0.2979725000.2797600773.136215>},#{amount => 1,key => <<"banane">>}],[{file,"lib/agent.ex"},{line,20}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.296.0>,{add,10},5000]}} in 'Elixir.GenServer':call/3 line 1027
2020-12-21 20:15:04.749 [error] <0.288.0> Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.290.0> exit with reason {{function_clause,[{'Elixir.CALC.Agent',handle_call,[{add,10},{<0.290.0>,#Ref<0.2979725000.2797600773.136215>},#{amount => 1,key => <<"banane">>}],[{file,"lib/agent.ex"},{line,20}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,[<0.296.0>,{add,10},5000]}} in context child_terminated
2020-12-21 21:23:55.452 [error] <0.290.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.298.0>}, [<0.300.0>|<0.297.0>]) line 14
2020-12-21 21:23:55.452 [error] <0.290.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.290.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.298.0>}, [<0.300.0>|<0.297.0>]) line 14
2020-12-21 21:23:55.452 [error] <0.287.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.290.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.298.0>}, [<0.300.0>|<0.297.0>]) line 14 in context child_terminated
2020-12-21 21:25:02.520 [error] <0.291.0>@Elixir.GenServer:cast:1058 gen_server resupply terminated with reason: no function clause matching 'Elixir.GenServer':cast([[[[]|<0.297.0>]|<0.299.0>]|<0.298.0>], {add,10}) line 1058
2020-12-21 21:25:02.521 [error] <0.291.0>@Elixir.GenServer:cast:1058 CRASH REPORT Process <0.291.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.GenServer':cast([[[[]|<0.297.0>]|<0.299.0>]|<0.298.0>], {add,10}) line 1058
2020-12-21 21:25:02.521 [error] <0.288.0>@Elixir.GenServer:cast:1058 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.291.0> exit with reason no function clause matching 'Elixir.GenServer':cast([[[[]|<0.297.0>]|<0.299.0>]|<0.298.0>], {add,10}) line 1058 in context child_terminated
2020-12-21 21:26:21.722 [error] <0.297.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.303.0>}, [<0.304.0>|<0.305.0>]) line 14
2020-12-21 21:26:21.723 [error] <0.297.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.297.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.303.0>}, [<0.304.0>|<0.305.0>]) line 14
2020-12-21 21:26:21.723 [error] <0.294.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.297.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.303.0>}, [<0.304.0>|<0.305.0>]) line 14 in context child_terminated
2020-12-21 21:26:27.031 [error] <0.308.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.306.0>}, [<0.305.0>|<0.307.0>]) line 14
2020-12-21 21:26:27.032 [error] <0.308.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.308.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.306.0>}, [<0.305.0>|<0.307.0>]) line 14
2020-12-21 21:26:27.032 [error] <0.294.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.308.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.306.0>}, [<0.305.0>|<0.307.0>]) line 14 in context child_terminated
2020-12-21 21:29:03.283 [error] <0.291.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.299.0>}, [<0.301.0>|<0.297.0>]) line 14
2020-12-21 21:29:03.284 [error] <0.291.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.291.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.299.0>}, [<0.301.0>|<0.297.0>]) line 14
2020-12-21 21:29:03.285 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.291.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.299.0>}, [<0.301.0>|<0.297.0>]) line 14 in context child_terminated
2020-12-21 21:29:07.270 [error] <0.302.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.301.0>}, [<0.300.0>|<0.298.0>]) line 14
2020-12-21 21:29:07.270 [error] <0.302.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.302.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.301.0>}, [<0.300.0>|<0.298.0>]) line 14
2020-12-21 21:29:07.270 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.302.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.301.0>}, [<0.300.0>|<0.298.0>]) line 14 in context child_terminated
2020-12-21 21:29:07.548 [error] <0.304.0>@Elixir.CALC.Resupply:handle_cast:14 gen_server resupply terminated with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.298.0>}, [<0.299.0>|<0.297.0>]) line 14
2020-12-21 21:29:07.548 [error] <0.304.0>@Elixir.CALC.Resupply:handle_cast:14 CRASH REPORT Process <0.304.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.298.0>}, [<0.299.0>|<0.297.0>]) line 14
2020-12-21 21:29:07.548 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:14 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.304.0> exit with reason no function clause matching 'Elixir.CALC.Resupply':handle_cast({resupply,<0.298.0>}, [<0.299.0>|<0.297.0>]) line 14 in context child_terminated
2020-12-21 21:29:49.576 [error] <0.291.0>@Elixir.CALC.Resupply:handle_cast:18 gen_server resupply terminated with reason: bad argument in call to erlang:'++'([<0.301.0>|<0.300.0>], <0.299.0>) in 'Elixir.CALC.Resupply':handle_cast/2 line 18
2020-12-21 21:29:49.576 [error] <0.291.0>@Elixir.CALC.Resupply:handle_cast:18 CRASH REPORT Process <0.291.0> with 0 neighbours crashed with reason: bad argument in call to erlang:'++'([<0.301.0>|<0.300.0>], <0.299.0>) in 'Elixir.CALC.Resupply':handle_cast/2 line 18
2020-12-21 21:29:49.576 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:18 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.291.0> exit with reason bad argument in call to erlang:'++'([<0.301.0>|<0.300.0>], <0.299.0>) in 'Elixir.CALC.Resupply':handle_cast/2 line 18 in context child_terminated
2020-12-21 21:29:51.850 [error] <0.302.0>@Elixir.CALC.Resupply:handle_cast:18 gen_server resupply terminated with reason: bad argument in call to erlang:'++'([<0.300.0>|<0.301.0>], <0.298.0>) in 'Elixir.CALC.Resupply':handle_cast/2 line 18
2020-12-21 21:29:51.851 [error] <0.302.0>@Elixir.CALC.Resupply:handle_cast:18 CRASH REPORT Process <0.302.0> with 0 neighbours crashed with reason: bad argument in call to erlang:'++'([<0.300.0>|<0.301.0>], <0.298.0>) in 'Elixir.CALC.Resupply':handle_cast/2 line 18
2020-12-21 21:29:51.851 [error] <0.288.0>@Elixir.CALC.Resupply:handle_cast:18 Supervisor 'Elixir.CALC.MainSupervisor' had child 'Elixir.CALC.Resupply' started with 'Elixir.CALC.Resupply':start_link([]) at <0.302.0> exit with reason bad argument in call to erlang:'++'([<0.300.0>|<0.301.0>], <0.298.0>) in 'Elixir.CALC.Resupply':handle_cast/2 line 18 in context child_terminated
2020-12-21 22:09:46.573 [error] <0.305.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:09:46.573 [error] <0.305.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.305.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:09:46.573 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.296.0>) at <0.305.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:09:46.574 [error] <0.303.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:09:46.574 [error] <0.303.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.303.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:09:46.574 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.296.0>) at <0.303.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:09:46.575 [error] <0.302.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:09:46.575 [error] <0.302.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.302.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:09:46.575 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.296.0>) at <0.302.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:09:46.576 [error] <0.306.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:09:46.576 [error] <0.306.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.306.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:09:46.576 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.296.0>) at <0.306.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:09:46.576 [error] <0.304.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:09:46.576 [error] <0.304.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.304.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:09:46.577 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.296.0>) at <0.304.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:14:32.800 [error] <0.298.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:14:32.800 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:14:32.800 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.290.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:14:32.801 [error] <0.299.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:14:32.801 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:14:32.801 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.290.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:14:32.802 [error] <0.296.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:14:32.802 [error] <0.296.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.296.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:14:32.802 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.290.0>) at <0.296.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:16:41.328 [error] <0.305.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:16:41.328 [error] <0.305.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.305.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:16:41.328 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.296.0>) at <0.305.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:16:41.329 [error] <0.306.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:16:41.329 [error] <0.306.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.306.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:16:41.329 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.296.0>) at <0.306.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:16:41.329 [error] <0.303.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:16:41.330 [error] <0.303.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.303.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:16:41.330 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.296.0>) at <0.303.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:16:41.330 [error] <0.302.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:16:41.330 [error] <0.302.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.302.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:16:41.330 [error] <0.294.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.296.0>) at <0.302.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:19:54.602 [error] <0.300.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:19:54.602 [error] <0.300.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:19:54.602 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.291.0>) at <0.300.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:19:54.603 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:19:54.603 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:19:54.603 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:19:54.603 [error] <0.298.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:19:54.603 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:19:54.603 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.291.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:20:51.269 [error] <0.300.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:20:51.269 [error] <0.300.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:20:51.270 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.291.0>) at <0.300.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:20:51.270 [error] <0.298.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:20:51.270 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:20:51.270 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.291.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:20:51.271 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:20:51.271 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:20:51.271 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:21:10.764 [error] <0.297.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:21:10.764 [error] <0.297.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:21:10.764 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.291.0>) at <0.297.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:21:10.765 [error] <0.299.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:21:10.765 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:21:10.765 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.291.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:21:10.766 [error] <0.298.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:21:10.766 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:21:10.766 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.291.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:21:10.767 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:21:10.767 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:21:10.767 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:22:36.793 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:22:36.793 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:22:36.793 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:22:36.794 [error] <0.297.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:22:36.794 [error] <0.297.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:22:36.794 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.291.0>) at <0.297.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:22:36.795 [error] <0.299.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:22:36.795 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:22:36.795 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.291.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:23:43.722 [error] <0.297.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:23:43.722 [error] <0.297.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:23:43.722 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.291.0>) at <0.297.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:23:43.723 [error] <0.300.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:23:43.723 [error] <0.300.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:23:43.723 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.291.0>) at <0.300.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:23:43.723 [error] <0.299.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:23:43.723 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:23:43.724 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.291.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:23:43.724 [error] <0.298.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:23:43.724 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:23:43.724 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.291.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:23:43.725 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:23:43.725 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:23:43.725 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:24:31.738 [error] <0.298.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:24:31.739 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:24:31.739 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.291.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:24:31.739 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:24:31.739 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:24:31.739 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:26:22.158 [error] <0.296.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:26:22.158 [error] <0.296.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.296.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:26:22.161 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.290.0>) at <0.296.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:26:22.161 [error] <0.299.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:26:22.161 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:26:22.161 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.290.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:26:22.161 [error] <0.298.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:26:22.162 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:26:22.162 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.290.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:26:22.162 [error] <0.300.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:26:22.162 [error] <0.300.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:26:22.162 [error] <0.288.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.290.0>) at <0.300.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:28:56.620 [error] <0.300.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:28:56.620 [error] <0.300.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:28:56.624 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.291.0>) at <0.300.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:28:56.624 [error] <0.297.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:28:56.624 [error] <0.297.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:28:56.624 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.291.0>) at <0.297.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:28:56.624 [error] <0.299.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:28:56.624 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:28:56.624 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.291.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:28:56.624 [error] <0.301.0> gen_server peche_agent terminated with reason: bad return value: nil
2020-12-21 22:28:56.624 [error] <0.301.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:28:56.624 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.291.0>) at <0.301.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:29:46.531 [error] <0.298.0> gen_server framboise_agent terminated with reason: bad return value: nil
2020-12-21 22:29:46.532 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:29:46.534 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.291.0>) at <0.298.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:29:46.534 [error] <0.297.0> gen_server banane_agent terminated with reason: bad return value: nil
2020-12-21 22:29:46.534 [error] <0.297.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:29:46.535 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.291.0>) at <0.297.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:29:46.535 [error] <0.299.0> gen_server pomme_agent terminated with reason: bad return value: nil
2020-12-21 22:29:46.535 [error] <0.299.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:29:46.535 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.291.0>) at <0.299.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 22:29:46.535 [error] <0.300.0> gen_server poire_agent terminated with reason: bad return value: nil
2020-12-21 22:29:46.535 [error] <0.300.0>@gen_server:handle_common_reply:800 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: nil in gen_server:handle_common_reply/8 line 800
2020-12-21 22:29:46.535 [error] <0.289.0> Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.291.0>) at <0.300.0> exit with reason bad return value: nil in context child_terminated
2020-12-21 23:17:16.959 [error] <0.282.0>@Elixir.CALC.Agent:init:11 CRASH REPORT Process <0.282.0> with 0 neighbours crashed with reason: no match of right hand value 2 in 'Elixir.CALC.Agent':init/1 line 11
2020-12-21 23:17:16.959 [error] <0.283.0>@Elixir.CALC.Agent:init:11 CRASH REPORT Process <0.283.0> with 0 neighbours crashed with reason: no match of right hand value 2 in 'Elixir.CALC.Agent':init/1 line 11
2020-12-21 23:17:16.959 [error] <0.284.0>@Elixir.CALC.Agent:init:11 CRASH REPORT Process <0.284.0> with 0 neighbours crashed with reason: no match of right hand value 2 in 'Elixir.CALC.Agent':init/1 line 11
2020-12-21 23:17:16.960 [error] <0.285.0>@Elixir.CALC.Agent:init:11 CRASH REPORT Process <0.285.0> with 0 neighbours crashed with reason: no match of right hand value 2 in 'Elixir.CALC.Agent':init/1 line 11
2020-12-21 23:17:16.960 [error] <0.286.0>@Elixir.CALC.Agent:init:11 CRASH REPORT Process <0.286.0> with 0 neighbours crashed with reason: no match of right hand value 2 in 'Elixir.CALC.Agent':init/1 line 11
2020-12-22 14:32:18.804 [error] <0.316.0>@Elixir.CALC.Agent:handle_continue:47 gen_server peche_agent terminated with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:18.804 [error] <0.313.0>@Elixir.CALC.Agent:handle_continue:47 gen_server framboise_agent terminated with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:18.804 [error] <0.312.0>@Elixir.CALC.Agent:handle_continue:47 gen_server banane_agent terminated with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:18.804 [error] <0.315.0>@Elixir.CALC.Agent:handle_continue:47 gen_server poire_agent terminated with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:18.804 [error] <0.315.0>@Elixir.CALC.Agent:handle_continue:47 CRASH REPORT Process <0.315.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:18.804 [error] <0.316.0>@Elixir.CALC.Agent:handle_continue:47 CRASH REPORT Process <0.316.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:18.804 [error] <0.312.0>@Elixir.CALC.Agent:handle_continue:47 CRASH REPORT Process <0.312.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:18.804 [error] <0.313.0>@Elixir.CALC.Agent:handle_continue:47 CRASH REPORT Process <0.313.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:18.805 [error] <0.304.0>@Elixir.CALC.Agent:handle_continue:47 Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"poire">>, 10, <0.306.0>, #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},...}) at <0.315.0> exit with reason no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47 in context child_terminated
2020-12-22 14:32:18.805 [error] <0.304.0>@Elixir.CALC.Agent:handle_continue:47 Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"peche">>, 10, <0.306.0>, #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},...}) at <0.316.0> exit with reason no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47 in context child_terminated
2020-12-22 14:32:18.805 [error] <0.304.0>@Elixir.CALC.Agent:handle_continue:47 Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"banane">>, 10, <0.306.0>, #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},...}) at <0.312.0> exit with reason no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47 in context child_terminated
2020-12-22 14:32:18.805 [error] <0.304.0>@Elixir.CALC.Agent:handle_continue:47 Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"framboise">>, 10, <0.306.0>, #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},...}) at <0.313.0> exit with reason no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 9,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47 in context child_terminated
2020-12-22 14:32:19.710 [error] <0.314.0>@Elixir.CALC.Agent:handle_continue:47 gen_server pomme_agent terminated with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:19.711 [error] <0.314.0>@Elixir.CALC.Agent:handle_continue:47 CRASH REPORT Process <0.314.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47
2020-12-22 14:32:19.711 [error] <0.304.0>@Elixir.CALC.Agent:handle_continue:47 Supervisor 'Elixir.CALC.AgentSupervisor' had child undefined started with 'Elixir.CALC.Agent':start(<<"pomme">>, 10, <0.306.0>, #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.290.0>},...}) at <0.314.0> exit with reason no function clause matching 'Elixir.CALC.Agent':handle_continue({check_notif,10}, #{amount => 8,channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 47 in context child_terminated
2020-12-22 15:24:18.523 [error] <0.294.0> Supervisor 'Elixir.CALC.ClientSupervisor' had child <<"clientTest">> started with 'Elixir.CALC.Client':init(<<"toto">>, [<<"peche.5">>]) at undefined exit with reason {'EXIT',{{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'calc_exchange' in vhost '/'">>}},{gen_server,call,[<0.308.0>,{subscribe,{'basic.consume',0,<<"calc_exchange">>,<<>>,false,true,false,false,[]},<0.310.0>},60000]}}} in context start_error
2020-12-22 16:32:55.988 [error] <0.291.0> CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 138
2020-12-22 16:36:03.115 [error] <0.291.0> CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 138
2020-12-22 16:38:11.401 [error] <0.291.0> CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 138
2020-12-22 16:40:26.186 [error] <0.293.0>@ok:init CRASH REPORT Process <0.293.0> with 0 neighbours crashed with reason: call to undefined function ok:init([{strategy,one_for_one},{name,'Elixir.CALC.ClientSupervisor'}])
2020-12-22 16:40:26.186 [error] <0.291.0> CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: {{undef,[{ok,init,[[{strategy,one_for_one},{name,'Elixir.CALC.ClientSupervisor'}]],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,301}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.CALC.Application',start,[normal,[]]}} in application_master:init/4 line 138
2020-12-22 16:41:06.104 [error] <0.291.0> CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: {{undef,[{ok,init,[[{strategy,one_for_one},{name,'Elixir.CALC.ClientSupervisor'}]],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,301}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.CALC.Application',start,[normal,[]]}} in application_master:init/4 line 138
2020-12-22 16:41:06.104 [error] <0.293.0>@ok:init CRASH REPORT Process <0.293.0> with 0 neighbours crashed with reason: call to undefined function ok:init([{strategy,one_for_one},{name,'Elixir.CALC.ClientSupervisor'}])
2020-12-22 16:45:16.561 [error] <0.293.0>@ok:init CRASH REPORT Process <0.293.0> with 0 neighbours crashed with reason: call to undefined function ok:init([{strategy,one_for_one},{name,'Elixir.CALC.ClientSupervisor'}])
2020-12-22 16:45:16.562 [error] <0.291.0> CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: {{undef,[{ok,init,[[{strategy,one_for_one},{name,'Elixir.CALC.ClientSupervisor'}]],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,301}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.CALC.Application',start,[normal,[]]}} in application_master:init/4 line 138
2020-12-22 17:17:08.069 [error] <0.299.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-e7mRKZCZ5lzAvRQJ3VS15Q">>}}
2020-12-22 17:17:08.070 [error] <0.299.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-ZDWJ4j_Y1F_jNcpVnKPJ7Q">>}}
2020-12-22 17:17:08.070 [error] <0.299.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-NULE9VqCrk0lObFBA0H2hg">>}}
2020-12-22 17:17:08.070 [error] <0.299.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-7ukL10Qrmn10b-78j9w4Tg">>}}
2020-12-22 17:17:08.070 [error] <0.299.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-VWRuHMr5N0xLCjDOjzCJMw">>}}
2020-12-22 17:25:43.351 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-rgcjzJ6QmtCIuKnKPPXEWw">>}}
2020-12-22 17:25:43.351 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-LzP_YmXhAg914_QIQZnM2Q">>}}
2020-12-22 17:25:43.351 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-lrWMukaTLbnkCM6dspy8hQ">>}}
2020-12-22 17:25:43.351 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-H-fuq4ATEAldHhqUZ2pQuQ">>}}
2020-12-22 17:25:43.351 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-w1x7xTBhqlH2u1WCpwxbYw">>}}
2020-12-22 17:27:20.337 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-n8onPFjX_NV93E1nrL1SfA">>}}
2020-12-22 17:27:20.337 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-x8BKSY2A7FPTV5HTggl7LQ">>}}
2020-12-22 17:27:20.337 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-fpF5-yZftk1edZ0V2qgrZg">>}}
2020-12-22 17:27:20.338 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-ZIDiIC3tlyDcHi4MtJsJkw">>}}
2020-12-22 17:27:20.338 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-v83aa3mCvnRiv7F2uEZ14Q">>}}
2020-12-22 17:28:26.092 [error] <0.294.0> Supervisor 'Elixir.CALC.ClientSupervisor' had child <<"1">> started with 'Elixir.CALC.Client':init(<<"client_1">>, [<<"framboise.0">>]) at undefined exit with reason {'EXIT',{{badmatch,<0.311.0>},[{'Elixir.CALC.Client',init,2,[{file,"lib/client.ex"},{line,15}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,...}]},...]}} in context start_error
2020-12-22 17:28:26.092 [error] <0.292.0> CRASH REPORT Process <0.292.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,<<"1">>,{'EXIT',{{badmatch,<0.311.0>},[{'Elixir.CALC.Client',init,2,[{file,"lib/client.ex"},{line,15}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,...},...]}}}},...} in application_master:init/4 line 138
2020-12-22 17:29:26.251 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-3t75e0uGpHbL7fLwMeKclg">>}}
2020-12-22 17:29:26.251 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-5FtIXQQDICaL65arC3ASCw">>}}
2020-12-22 17:29:26.252 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-qgNJBOs0sPXbhJRoI6jGQw">>}}
2020-12-22 17:29:26.252 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-31OLQvu0VMPjBJn2aFKMFA">>}}
2020-12-22 17:29:26.253 [error] <0.294.0> Supervisor received unexpected message: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-owt3xyssdHFF3e4yc6Fjyg">>}}
2020-12-22 18:42:03.567 [error] <0.334.0> gen_server <0.334.0> terminated with reason: socket_closed_unexpectedly
2020-12-22 18:42:03.568 [error] <0.337.0> gen_server <0.337.0> terminated with reason: socket_closed_unexpectedly
2020-12-22 18:42:03.568 [error] <0.340.0> gen_server <0.340.0> terminated with reason: socket_closed_unexpectedly
2020-12-22 18:42:03.568 [error] <0.331.0> gen_server <0.331.0> terminated with reason: socket_closed_unexpectedly
2020-12-22 18:42:03.569 [error] <0.328.0> gen_server <0.328.0> terminated with reason: socket_closed_unexpectedly
2020-12-22 18:42:03.569 [error] <0.328.0> CRASH REPORT Process <0.328.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 796
2020-12-22 18:42:03.570 [error] <0.337.0> CRASH REPORT Process <0.337.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 796
2020-12-22 18:42:03.570 [error] <0.334.0> CRASH REPORT Process <0.334.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 796
2020-12-22 18:42:03.570 [error] <0.331.0> CRASH REPORT Process <0.331.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 796
2020-12-22 18:42:03.570 [error] <0.340.0> CRASH REPORT Process <0.340.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 796
2020-12-22 18:42:03.570 [error] <0.325.0> Supervisor {<0.325.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.327.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.328.0> exit with reason socket_closed_unexpectedly in context child_terminated
2020-12-22 18:42:03.570 [error] <0.329.0> Supervisor {<0.329.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.330.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.331.0> exit with reason socket_closed_unexpectedly in context child_terminated
2020-12-22 18:42:03.570 [error] <0.325.0> Supervisor {<0.325.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.327.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.328.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-22 18:42:03.571 [error] <0.329.0> Supervisor {<0.329.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.330.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.331.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-22 18:42:03.571 [error] <0.335.0> Supervisor {<0.335.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.336.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.337.0> exit with reason socket_closed_unexpectedly in context child_terminated
2020-12-22 18:42:03.571 [error] <0.335.0> Supervisor {<0.335.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.336.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.337.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-22 18:42:03.571 [error] <0.338.0> Supervisor {<0.338.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.339.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.340.0> exit with reason socket_closed_unexpectedly in context child_terminated
2020-12-22 18:42:03.571 [error] <0.338.0> Supervisor {<0.338.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.339.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.340.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-22 18:42:03.571 [error] <0.332.0> Supervisor {<0.332.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.333.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.334.0> exit with reason socket_closed_unexpectedly in context child_terminated
2020-12-22 18:42:03.572 [error] <0.332.0> Supervisor {<0.332.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.333.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"172.17.0.2",5672,0,0,10,50000,...}) at <0.334.0> exit with reason reached_max_restart_intensity in context shutdown
2020-12-22 18:50:44.159 [error] <0.291.0>@Elixir.CALC.Application:start CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: bad return value ok from 'Elixir.CALC.Application':start(normal, []) in application_master:init/4 line 138
2020-12-22 18:51:23.508 [error] <0.291.0>@Elixir.CALC.Application:start CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: bad return value ok from 'Elixir.CALC.Application':start(normal, []) in application_master:init/4 line 138
2020-12-22 21:33:51.264 [error] <0.285.0>@Elixir.CALC.Application:start:24 CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: no match of right hand value {error,econnrefused} in 'Elixir.CALC.Application':start/2 line 24 in application_master:init/4 line 138
2020-12-22 21:35:21.856 [error] <0.285.0>@Elixir.CALC.Application:start:24 CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: no match of right hand value {error,econnrefused} in 'Elixir.CALC.Application':start/2 line 24 in application_master:init/4 line 138
